services:
  # Skill Forge Backend Database
  skill-forge-backend:
    image: postgres:16
    container_name: skill_forge_db
    hostname: skill_forge_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: $POSTGRES_DB}
      TZ: ${TZ}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - auth_db:/var/lib/postgresql/data
    networks:
      - skill_forge_network

  # Piston API
  piston-api:
    # image: ghcr.io/engineer-man/piston
    image: ghcr.io/engineer-man/piston@sha256:6500f2af69ce18fe16ca9a0ba7b0ea895366fc0efa46860c03d1d3c8a6cd270d
    container_name: piston-api
    hostname: pistonapi
    restart: unless-stopped
    privileged: true
    ports:
      - 2000:2000
    volumes:
      - ./data/piston/packages:/piston/packages
    tmpfs:
      - /tmp:exec
    networks:
      - skill_forge_network



volumes:
  auth_db:
    driver: local
    name: skill_forge_db


networks:
  skill_forge_network:
    driver: bridge
    name: skill_forge_network
