version: '3.8'
services:

  # Skill-Forge application
  skill-forge-app:
    image: skillforge-app:1.0
    build:
      context: .
      dockerfile: Dockerfile 
    container_name: skillforge-app
    restart: on-failure
    ports:
      - '5005:5000'
    volumes:
      - /app:/app

  # Development PostgreSQL database instance
  db:
    image: postgres
    container_name: skillforge-postgres-dev
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  
  # Production PostgreSQL database instance
  db-production:
    image: postgres
    container_name: skillforge-postgres-prod
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER_PROD}
      - POSTGRES_PASSWORD=${DB_PASSWORD_PROD}
      - POSTGRES_DB=${DB_NAME_PROD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - '5433:5432'
    volumes: 
      - db-prod:/var/lib/postgresql/data


  # The node server is being used to serve the unit test execution for the JS quests on port 3000
  js-server:
    build:
      context: ./js-backend-server
      dockerfile: Dockerfile
    container_name: skillforge-js-server-dev
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - ./js-backend-server/server:/app


volumes:
  skill-forge-app:
    driver: local

  js-server:
    driver: local

  db:
    driver: local
    
  db-prod:
    driver: local