services:

  # Development PostgreSQL database instance
  postgres-dev:
    build:
      context: .
      dockerfile: ./Dockerfile.postgres
    container_name: skillforge-postgres-dev
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    volumes:
      - postgres-dev:/var/lib/postgresql/data/pgdata
  
  # MongoDB database replica cluster
  mongo1-master:
    image: mongo:4.4.18
    container_name: mongo1
    command: mongod --replSet rs0 --bind_ip localhost,mongo1
    ports:
      - "27017:27017"
    volumes:
      - mongo1-master:/data/db

  mongo2-slave:
    image: mongo:4.4.18
    container_name: mongo2
    command: mongod --replSet rs0 --bind_ip localhost,mongo2
    ports:
      - "27018:27017"
    volumes:
      - mongo2-slave:/data/db

  mongo3-slave:
    image: mongo:4.4.18
    container_name: mongo3
    command: mongod --replSet rs0 --bind_ip localhost,mongo3
    ports:
      - "27019:27017"
    volumes:
      - mongo3-slave:/data/db

  # Skill Forge application dev instance
  skill-forge-dev:
    build:
      context: .
      dockerfile: ./Dockerfile.skill_forge
    container_name: skillforge-dev
    restart: always
    ports:
      - '8000:8000'
    volumes:
      - skill-forge-dev:/app
    depends_on:
      - postgres-dev
      - mongo1-master
      - mongo2-slave
      - mongo3-slave




volumes:
  postgres-dev:
    driver: local
  mongo1-master:
    driver: local
  mongo2-slave:
    driver: local
  mongo3-slave:
    driver: local
  skill-forge-dev:
    driver: local
