services:

  # Development PostgreSQL database instance
  postgres-dev:
    build:
      context: .
      dockerfile: ./Dockerfile.postgres
    container_name: skillforge-postgres-dev
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    volumes:
      - postgres-dev:/var/lib/postgresql/data/pgdata
      - ./achievements.sql:/docker-entrypoint-initdb.d/achievements.sql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command:
      - "postgres"
      - "-c"
      - "shared_preload_libraries=pg_cron"
      - "-c"
      - "cron.database_name=${DB_NAME}"
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "localhost", "-p", "5432"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - skillforge-net
  
  # MongoDB database replica cluster
  mongo-dev:
    image: mongo:4.4.18
    container_name: mongo-dev
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ADMIN_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ADMIN_PASSWORD}
    volumes:
      - mongo-dev:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    networks:
      - skillforge-net

  # Piston API instance
  piston-api:
    image: ghcr.io/engineer-man/piston@sha256:6500f2af69ce18fe16ca9a0ba7b0ea895366fc0efa46860c03d1d3c8a6cd270d
    container_name: piston-api
    ports:
      - "2000:2000"
    privileged: true
    volumes:
      - ../data/piston/packages:/piston/packages
    tmpfs:
      - /tmp:exec
    networks:
      - skillforge-net

  # Skill Forge application dev instance
  skill-forge-dev:
    build:
      context: .
      dockerfile: ./Dockerfile.skill_forge
    container_name: skillforge-dev
    restart: always
    ports:
      - '8000:8000'
    volumes:
      - skill-forge-dev:/app
    depends_on:
      - postgres-dev
      - mongo-dev
      - piston-api
    networks:
      - skillforge-net



volumes:
  postgres-dev:
    driver: local
  mongo-dev:
    driver: local
  skill-forge-dev:
    driver: local

networks:
  skillforge-net:
    driver: bridge
    